# Generated by Django 3.2.9 on 2022-01-27 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_verses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None),
        ),
    ]
