# Generated by Django 3.2.9 on 2022-03-10 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_prayerrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saved_verses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
