# Generated by Django 3.2.9 on 2022-05-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_saved_verses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(null=True, upload_to='Pictures/koffie.jpg'),
        ),
    ]
