# Generated by Django 4.1.5 on 2023-01-27 12:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=500)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2023, 1, 27, 12, 52, 31, 871200))),
                ('commentedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
