# Generated by Django 3.2.9 on 2022-03-09 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_versecomments_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='versecomments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='versecomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 19, 7, 35, 383125)),
        ),
    ]
