# Generated by Django 3.2.9 on 2022-03-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20220309_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versecomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 19, 28, 52, 194234)),
        ),
    ]
