# Generated by Django 3.2.9 on 2022-05-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_versecomments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versecomments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 17, 32, 37, 726452)),
        ),
    ]
